swagger: "2.0"
info:
  description: "International Seller API Documentation"
  version: "1.0.0"
  title: "International Seller"
  contact:
    email: "oussama.sidgui@isochronix.com"
host: "cdiscount--dev.my.salesforce.com"
basePath: "/services/apexrest/ICV"
tags:
- name: "Seller"
  description: "Parent Shop"
- name: "Subscription"
  description: "Child Shop & Related Opportunity"
schemes:
- "https"
paths:
  /seller:
    put:
      tags:
      - "Seller"
      summary: "Update an existing Parent Shop"
      description: "Update an existing Parent Shop"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Seller"
      responses:
        "400":
          description: "Failed Operation"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "200":
          description: "Success Operation"
          schema:
            $ref: "#/definitions/SellerResponse"
      security:
      - api_auth:
        - "write:sellers"
        - "read:sellers"
  /subscription:
    post:
      tags:
      - "Subscription"
      summary: "Create New Child Shop & Opportunity"
      description: "Create New Child Shop & Opportunity"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Subscription"
      responses:
        "400":
          description: "Failed Operation"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "200":
          description: "Success Operation"
          schema:
            $ref: "#/definitions/SubscriptionResponse"
      security:
      - api_auth:
        - "write:sellers"
        - "read:sellers"      
        
securityDefinitions:
  api_auth:
    type: "oauth2"
    tokenUrl: "https://test.salesforce.com/services/oauth2/token"
    flow: "password"
    scopes:
      write:sellers: "modify selelrs"
      read:sellers: "read sellers"
definitions:
  Seller:
    type: "object"
    required:
    - "sellerId"
    - "substate"
    - "status"
    - "state"
    - "isFulfillment"
    properties:
      sellerId:
        type: "integer"
        example: "19454"
      substate:
        type: "string"
        example: "holidays"
      status:
        type: "string"
        example: "refused"
      state:
        type: "string"
        example: "activated"
      isFulfillment:
        type: "boolean"
        example: "false"
  Subscription:
    type: "object"
    required:
    - "sellerId"
    - "substate"
    - "status"
    - "state"
    - "isFulfillment"
    properties:
      salesChannelId:
        type: "string"
        example: "CASIFR"
      sellerId:
        type: "integer"
        example: 183919
      status:
        type: "string"
        example: "Subscribed"
      state:
        type: "string"
        example: "Terminated"
      action:
        type: "string"
        example: "activate"
  ErrorResponse:
    type: "object"
    properties:
      Status:
        type: "string"
        example: 400
      Message:
        type: "string"
        example : "SalesForce Error Message"
  SellerResponse:
    type: "object"
    properties:
      Status:
        type: "string"
        example: 200
      Message:
        type: "string"
        example : "Account Id : 10114545421"
  SubscriptionResponse:
    type: "object"
    properties:
      Status:
        type: "string"
        example: 200
      Message:
        type: "string"
        example : "Account Id : 10114545421 Opportunity Id : 123456465467"
